### ISSUE TITLE
Install jx3 on existing EKS cluster

### ISSUE THREAD

**Issue by maiakhoa** [jx3-gitops-repositories/jx3-terraform-eks#19]
do we have any chance to install jx3 on existing EKS cluster?

**Comment by ankitm123** [comment]
https://github.com/jenkins-x/terraform-aws-eks-jx/tree/master/examples/existing-cluster -> See this. You may need to change few things, but I have been using this setting for months now at my company.

**Comment by maiakhoa** [comment]
thank @ankitm123 for quick answer, let me try that

**Comment by ankitm123** [comment]
FWIW this is what I have:
```
module "jx" {
  source                         = "jenkins-x/eks-jx/aws"
  version                        = "1.15.37"
  region                         = var.region
  use_vault                      = var.use_vault
  cluster_name                   = var.cluster_name
  is_jx2                         = var.is_jx2
  create_eks                     = var.create_eks
  create_vpc                     = var.create_vpc
  jx_git_url                     = var.jx_git_url
  jx_bot_username                = var.jx_bot_username
  jx_bot_token                   = var.jx_bot_token
  force_destroy                  = var.force_destroy
  create_autoscaler_role         = var.create_autoscaler_role
  create_tekton_role             = var.create_tekton_role
  create_and_configure_subdomain = var.create_and_configure_subdomain
  apex_domain                    = var.apex_domain
  subdomain                      = var.subdomain
  manage_apex_domain             = var.manage_apex_domain
  manage_subdomain               = var.manage_subdomain
  cluster_version                = var.cluster_version
  nginx_chart_version            = "3.12.0"
}
```

**Comment by maiakhoa** [comment]
thank @ankitm123 I can run it now. But I see that even I set create_eks = false, the log file is showing that it will create the cluster

```
# module.eks.aws_eks_cluster.this[0] will be created
  + resource "aws_eks_cluster" "this" {
      + arn                   = (known after apply)
      + certificate_authority = (known after apply)
      + created_at            = (known after apply)
      + endpoint              = (known after apply)
      + id                    = (known after apply)
      + identity              = (known after apply)
      + name                  = "GOLFTEC"
      + platform_version      = (known after apply)
      + role_arn              = (known after apply)
      + status                = (known after apply)
      + tags_all              = (known after apply)
      + version               = "1.18"

      + kubernetes_network_config {
          + service_ipv4_cidr = (known after apply)
        }

      + timeouts {
          + create = "30m"
          + delete = "15m"
        }

      + vpc_config {
          + cluster_security_group_id = (known after apply)
          + endpoint_private_access   = false
          + endpoint_public_access    = true
          + public_access_cidrs       = [
              + "0.0.0.0/0",
            ]
          + security_group_ids        = (known after apply)
          + subnet_ids                = (known after apply)
          + vpc_id                    = (known after apply)
        }
    }
```
It happens that VPC and Worker Group will be created as well.
Please help to correct if I miss any

Thanks!

**Comment by ankitm123** [comment]
what value do u have for create_eks? Are they set to false?

**Comment by maiakhoa** [comment]
[variables.txt](https://github.com/jx3-gitops-repositories/jx3-terraform-eks/files/7140547/variables.txt)
[main.txt](https://github.com/jx3-gitops-repositories/jx3-terraform-eks/files/7140548/main.txt)

@ankitm123 those are the file I'm using

thanks!

**Comment by ankitm123** [comment]
ok, I see the confusion. You dont need anything about line 138, the example was to demonstrate that if there is a VPC created before hand, and an eks cluster was created inside it, we can still install jx inside that eks cluster. To test that example, I needed to create a vpc and eks cluster some how, so I created it in that file. You just need stuff from line 139. And then you can trim the variables.tf file.

**Comment by maiakhoa** [comment]
thank @ankitm123 so I'm going to use main.tf like below

```
data "aws_availability_zones" "available" {}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

// The VPC and EKS resources have been created, just install the cloud resources required by jx
module "jx" {
  source                         = "jenkins-x/eks-jx/aws"
  version                        = "1.15.38"
  region                         = var.region
  use_vault                      = false
  cluster_name                   = var.cluster_name
  is_jx2                         = true
  create_eks                     = false
  create_vpc                     = false
  jx_git_url                     = var.jx_git_url
  jx_bot_username                = var.jx_bot_username
  jx_bot_token                   = var.jx_bot_token
  force_destroy                  = var.force_destroy
  cluster_version                = var.cluster_version
  nginx_chart_version            = "3.12.0"
}
```

**Comment by ankitm123** [comment]
Yes imo.

**Comment by maiakhoa** [comment]
thank @ankitm123 there are no such creations anymore. But sorry, could you please help to send me these variables part in variables.tf?

  ```
create_autoscaler_role         = var.create_autoscaler_role
  create_tekton_role             = var.create_tekton_role
  create_and_configure_subdomain = var.create_and_configure_subdomain
  apex_domain                    = var.apex_domain
  subdomain                      = var.subdomain
  manage_apex_domain             = var.manage_apex_domain
  manage_subdomain               = var.manage_subdomain
```

**Comment by maiakhoa** [comment]
thank @ankitm123 I got it

**Comment by ankitm123** [comment]
The docs in the terraform module should have all the information: https://github.com/jenkins-x/terraform-aws-eks-jx

**Comment by maiakhoa** [comment]
@ankitm123 I applied the plan, but there are just some AWS resources are created. I have not seen any deployment or service for Jenkins. Do I miss any param?

Thanks!

**Comment by ankitm123** [comment]
Can you post the output from terraform plan, hard to say without looking at one? Also need to set `use_vault` to true, unless u have another secret storage configured.

**Comment by maiakhoa** [comment]
@ankitm123 please help to take a look
[out.txt](https://github.com/jx3-gitops-repositories/jx3-terraform-eks/files/7140871/out.txt)

**Comment by ankitm123** [comment]
looks ok to me, but u need vault set up, use_vault = true should do it.

**Comment by ankitm123** [comment]
Also the next steps are documented here: https://github.com/jx3-gitops-repositories/jx3-terraform-eks#getting-started. You should have a cluster git repo and all that ...

**Comment by maiakhoa** [comment]
I did all of those steps @ankitm123.

**Comment by ankitm123** [comment]
I dont see any vault in the output is missing vault, if u set it to true, and did an apply again, u can use `jx admin log` to see if everything succeeded. You should also configure a domain/subdomain, there are variables for that, so that you can have webhooks and dashboard set up. In the end, try jx project import to import repos into JX.

**Comment by maiakhoa** [comment]
thank @ankitm123 I got this error 

`MountVolume.SetUp failed for volume "secrets-git" : secrets "tekton-git" not found`

**Comment by maiakhoa** [comment]
it seems there is a problem when initializing vault. I got this error

`core: security barrier not initialized`

**Comment by tushae01** [comment]
as a heads, I'm having issues with missing secrets and configmaps when trying to install on an existing cluster this week, but it did work for me previously... this was my main.tf  (eks cluster is 1.19)- 
module "eks-jx" {
  source               = "github.com/jenkins-x/terraform-aws-eks-jx?ref=v1.15.12"
  cluster_name         = var.cluster_name
  cluster_version      = var.cluster_version
  region               = var.region
  vault_user           = var.vault_user
  use_vault            = true
  use_asm              = false
  is_jx2               = false
  create_eks           = false // Skip EKS creation
  create_vpc           = false // skip VPC creation
  jx_git_url           = var.jx_git_url
  jx_bot_username      = var.jx_bot_username
  jx_bot_token         = var.jx_bot_token
  force_destroy        = var.force_destroy
  install_kuberhealthy = var.install_kuberhealthy
}

**Comment by maiakhoa** [comment]
hi @tushae01 thank you

That issue has been solved. But I think I faced that because of multiple applying the stack I guess. And because I'm running on 1.21 so there was a few issues with latest version.

Thanks!

**Comment by ankitm123** [comment]
Change 
`source = "github.com/jenkins-x/terraform-aws-eks-jx?ref=v1.15.12"`

 to
`source = "github.com/jenkins-x/terraform-aws-eks-jx"`

**Comment by ankitm123** [comment]
/close
closing this as the main issue was solved, feel free to re-open or open another issue if there are other issues.
