### ISSUE TITLE
Confusion on versioning

### ISSUE THREAD

**Issue by mrmarcsmith** [jx3-gitops-repositories/jx3-terraform-eks#21]
Quick Question: in main.tf what purpose does the `?ref=v1.15.12` serve? aren't we defining the version on the next line down?

```
  source               = "jenkins-x/eks-jx/aws?ref=v1.15.12"
  version              = "1.15.38"
```

**Comment by ankitm123** [comment]
Everytime I removed it in the past, it comes back when the automated job runs. You can see it was added back by this commit sometime back: https://github.com/jx3-gitops-repositories/jx3-terraform-eks/commit/49eb70c79d8522eb923365a2ba7ff2606b89d117
I will track down where it's coming from, and get a fix. But for now, safe to just remove `?ref=v1.15.12`

**Comment by mrmarcsmith** [comment]
Thank you for the quick reply!
