### ISSUE TITLE
Stuck at boot time

### ISSUE THREAD

**Issue by maiakhoa** [jx3-gitops-repositories/jx3-terraform-eks#25]
I always get this error at external secret service 

```
{"level":50,"time":1631961555887,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/jenkins-maven-settings"}
{"level":50,"time":1631961555891,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/jenkins-x-chartmuseum"}
{"level":50,"time":1631961555892,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/tekton-git"}
{"level":50,"time":1631961555893,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/jx-basic-auth-user-password"}
{"level":50,"time":1631961555894,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx-staging/tekton-container-registry-auth"}
{"level":50,"time":1631961555896,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/lighthouse-hmac-token"}
{"level":50,"time":1631961555897,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/tekton-container-registry-auth"}
{"level":50,"time":1631961555899,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/lighthouse-oauth-token"}
{"level":50,"time":1631961555911,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/nexus"}
{"level":50,"time":1631961555912,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx/jx-basic-auth-htpasswd"}
{"level":50,"time":1631961555913,"pid":18,"hostname":"kubernetes-external-secrets-7686994b8c-xd2jm","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret jx-production/tekton-container-registry-auth"}
```

Few day ago I can start the stack normally, after I changed nexus storage, I always get that even rollback the change. Please advice

Thanks!

**Comment by maiakhoa** [comment]
```
Error from server (InternalError): error when creating "config-root/namespaces/jx/jx-pipelines-visualizer/jx-pipelines-visualizer-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
Error from server (InternalError): error when creating "config-root/namespaces/jx/jxboot-helmfile-resources/chartmuseum-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
Error from server (InternalError): error when creating "config-root/namespaces/jx/jxboot-helmfile-resources/hook-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
Error from server (InternalError): error when creating "config-root/namespaces/jx/jxboot-helmfile-resources/nexus-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found

```

This is the error from the first boot

**Comment by ankitm123** [comment]
>failure while polling the secret jx-production/tekton-container-registry-auth

Check if you have this secret in your storage backend ( iirc, you use vault), 404 suggests that it does not exist.

**Comment by maiakhoa** [comment]
I thought it is auto popular when starting the boot. How can I invoke to generate it again?

**Comment by maiakhoa** [comment]
After running `terraform apply`, I copied the output of jx-requirement and put to the cluster git, then commit the change. Is this step correct?

**Comment by maiakhoa** [comment]
do we have any way to turn off Vault? I just would like to launch the stack and making build like JenkinsX 2

**Comment by ankitm123** [comment]
> This is the error from the first boot

This is weird, not sure why you are missing those services ... did you follow the documentation? Also with a few lines, I cannot help in debugging, can you create a gist of the whole log from the first boot log, that would have all the information.

> I cleaned the whole stack and recreated but still got the error.

How did you clean the whole stack?

>  I copied the output of jx-requirement and put to the cluster git, then commit the change. Is this step correct?

No, is it mentioned somewhere? If yes, let me know, and I will modify the documentation

> do we have any way to turn off Vault?

I have not tried this, but why do you want to turn off vault? The error from the first boot clearly show that it did go to the stage where secrets would get auto populated ...

Also a bit confused, did you not get a working solution yesterday?

**Comment by maiakhoa** [comment]
@ankitm123 I got a working solution yesterday, but I would like to increase nexus storage. Then I destroy from terraform and deleted all namespace that had created. Then I started to run again and got that error

[jx-boot-2e2963d9-684e-403c-93cb-620b19cc5549-h4d4h.log](https://github.com/jx3-gitops-repositories/jx3-terraform-eks/files/7190105/jx-boot-2e2963d9-684e-403c-93cb-620b19cc5549-h4d4h.log)
This is the whole log from the first boot log.

Thanks!

**Comment by ankitm123** [comment]
>  Then I destroy from terraform and deleted all namespace that had created

Terraform destroy will destroy the cluster completely, not sure what you mean by delete all namespace...

> This is the whole log from the first boot log.

I will take a look, and get back to you.

**Comment by maiakhoa** [comment]
I have not seen it delete resource from the cluster, so I usually have to manually delete. Do I miss any?
And after I run `terraform apply`, jx-requirement is not updated to the cluster git. I also usually have to commit it manually. I followed the doc.

**Comment by ankitm123** [comment]
> I have not seen it delete resource from the cluster, so I usually have to manually delete. 

Ah i remember, you are installing into existing cluster, and not using the jx module to create eks cluster, makes sense.

> And after I run terraform apply, jx-requirement is not updated to the cluster git.

It's not supposed to, terraform apply should create a config map in the default namespace, it's different from the jx-requirements.yml in the cluster git repo iirc.

**Comment by maiakhoa** [comment]
yes @ankitm123 that is right.
this is mine

```
module "eks-jx" {
  source                         = "../../"
  region                         = "us-east-1"
  use_vault                      = true
  cluster_name                   = var.cluster_name
  is_jx2                         = false
  create_eks                     = false
  create_vpc                     = false
  jx_git_url                     = var.jx_git_url
  jx_bot_username                = var.jx_bot_username
  jx_bot_token                   = var.jx_bot_token
  force_destroy                  = var.force_destroy
  enable_external_dns            = var.enable_external_dns
  create_autoscaler_role         = var.create_autoscaler_role
  create_tekton_role             = var.create_tekton_role
  create_and_configure_subdomain = var.create_and_configure_subdomain
  apex_domain                    = var.apex_domain
  subdomain                      = var.subdomain
  manage_apex_domain             = var.manage_apex_domain
  manage_subdomain               = var.manage_subdomain
  cluster_version                = var.cluster_version
  nginx_chart_version            = "3.12.0"
}
```

**Comment by maiakhoa** [comment]
so as you mentioned, my action on updating after applying is unnecessary

**Comment by maiakhoa** [comment]
I just rerun and this is another log

https://gist.github.com/maiakhoa/b4c1effad5bf4bec83a43c66954d948c

**Comment by maiakhoa** [comment]
@ankitm123 I can start JX 3 now. I have to install Nginx first from this https://kubernetes.github.io/ingress-nginx/deploy/#aws

After that, I reinit and it's working now.

Thank you so much for supporting!

**Comment by ankitm123** [comment]
>  I have to install Nginx first from this

This should get installed when installing jx :confused:

**Comment by maiakhoa** [comment]
thank @ankitm123
