### ISSUE TITLE
Fresh install fails on terraform plan

### ISSUE THREAD

**Issue by alefr** [jx3-gitops-repositories/jx3-terraform-eks#26]
I tried following the getting started guide according to the README with fresh repos and as far as I can tell I have all prerequisites setup but it failed in a few ways a long the way.

I found issue #22 which helped me get passed the initial `terraform init` error by removing the ref as suggested and running with `terraform init -upgrade`.

But while @mrmarcsmith managed to run `terraform plan` I get the following error:

![image](https://user-images.githubusercontent.com/681046/135461579-c4b21bdb-1b87-432b-972f-1270f585a6f3.png)

I take it it fails to fetch the needed iam user/role for the eks worker? Is this something that the terraform scripts are creating or am I failing in providing something?

As you probably can tell I'm new to Terraform and have tried looking for information to get around this but failed.

I've tried with different versions of the `jx-eks` module with the latest being `1.16.1`.

As others have managed to bypass the plan step I take it I'm missing something, but I've gone through the readme several times and fail to see what, and being new to Terraform is kind of crippling in this case.

Happy to provide any other information needed.
Hoping anyone is able to see what I'm missing
Thanks

**Comment by alefr** [comment]
Borrowing from @mrmarchsmith good example of how to illustrate the changes made to the repo:
![image](https://user-images.githubusercontent.com/681046/135527296-44590c98-cf58-4edf-a691-6917a3d98412.png)

Exported the following env vars
```
export TF_VAR_jx_bot_token=<REDACTED>
export AWS_PROFILE=jx3
```

~/.aws/credentials file:
```
[default]
aws_access_key_id = <REDACTED>
aws_secret_access_key = <REDACTED>

[jx3]
aws_access_key_id = <REDACTED>
aws_secret_access_key = <REDACTED>
```

~/.aws/config:
```
[default]
region = eu-north-1
output = json

[profile jx3]
region = eu-north-1
output = json
```

**Comment by ankitm123** [comment]
> I've tried with different versions of the jx-eks module with the latest being 1.16.1.

You need to delete the cached/lock files/folders in terraform folder from older versions
```
rm -rf .terraform* terraform.lock.hcl
```

**Comment by alefr** [comment]
Yes, you're right, that solved it.

I was in there touching the on the lines, but my knowledge about how it all connected together was too low.
Thank you for the help @ankitm123 !
